--- 
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: origin-cli
  namespace: ontampa-devs-gaming
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: quay.io/openshift/origin-cli
    generation: 1
    importPolicy:
      importMode: Legacy
    name: "4.18"
    referencePolicy:
      type: Source
  - annotations: null
    from:
      kind: ImageStreamImage
      name: origin-cli@sha256:70a9d90b26fda37696086c3c1e77c4f79f4a525896f515608e33ddf160620639
    importPolicy:
      importMode: Legacy
    name: lastest
    referencePolicy:
      type: Source
